server:
    port: 8080
    servlet:
        context-path: /bootcamp

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: postgres://xeybyhsptfwzgf:efe597494c74acf02671b84b7390bbfcfc64209f2fa55a2d4df08c4706a1038f@ec2-23-23-128-222.compute-1.amazonaws.com:5432/d6pl1vlv7f0fat
        username: xeybyhsptfwzgf
        password: d6pl1vlv7f0fat
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        open-in-view: false
        hibernate:
            ddl-auto: none

application:
    description: Projeto criado para o bootcamp DIO - Santander
    version: 1.0
